services:
  api:
    build: .
    image: dm-api:v1
    environment:
      - PORT=3000
    ports:
      - 3000:3000 # "hote:conteneur"
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/volume/openapi:ro
    ports:
      - 8080:8080
    depends_on:
      - api