services:
  api:
    build: ./api
    image: dm-api:v1
    environment:
      - PORT=${PORT}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dernier_metro
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - 8080:8080
    depends_on:
      - api
      - postgres 

volumes:
  pgdata: