services:
  api:
    build: .
    image: dc-api:v1
    environment:
      - PORT=5000
    ports:
      - 5000:5000 # "hote:conteneur"
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=openapi.yaml
    volumes:
      - .openapi.yaml:app/openapi.yaml
    ports:
      - 8080:8080
    depends_on:
      - api