services:
  api:
    build: .
    image: dm-api:v1
    ports:
      - 3000:3000 # "hote:conteneur"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/volume/openapi:ro
    ports:
      - 8080:8080
    depends_on:
      - api